version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-api-tostrike
    build: .
    ports:
      - 8080:8080
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: tostrike
    ports:
      - "5432:5432"

volumes:
  pgdata: {}