version: "3.9"

services:
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: tostrike
    ports:
      - "5432:5432"

volumes:
  pgdata: {}